version: "3"

services:
  app:
    entrypoint: npm run start
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.3
    volumes:
      - volume-db:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
volumes:
  volume-db:
